contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search_contact'), # Buscar objetos pelo first_name ou last_name

    # contact (CRUD)
    path('contact/<int:contact_id>/', views.get_contact, name='get_contact'), # buscar por um conatcto
    path('contact/create/', views.create, name='create_contact'), # Criar um contacto
    path('contact/<int:contact_id>/update', views.update, name='update_contact'), # Atualizar um contacto
    path('contact/<int:contact_id>/delete', views.delete, name='delete_contact'),

    # user
    path('user/create_user', views.create_user, name='create_user'),

    path('user/login', views.login_user, name='login'),
    path('user/logout', views.logout_user, name='logout'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

# O MEDIA_URL é o nome do diretório onde estão as imagens e o MEDIA_ROOT é o caminho a ser seguido para acessar o diretório das imagens. Essa linha é para servimos a nossa página os aquivos enviados pelo usuário.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

"""
Campos do model
    id (primary key - automático)
    first_name (charfield)
    last_name (charfield)
    phone (charfield)
    email (emailfeed)
    create_date (datafield)
    description (textfield)

    category (foreign key)
    show (boolean)
    owner (foreign key)
    picture (imagefield)

"""

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"


   
class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True, null=True
        )
    
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True, null=True
        ) # Esse campo serve para informar o proprietário do contato. Está linkado a clase (model) User do django (from django.contrib.auth.models import User)
    
    def __str__(self):
        return self.first_name
    
    class Meta:
        verbose_name = "Cotacto"
        verbose_name_plural = "Contactos"

    

contact/forms.py
from typing import Any
from contact.models import Contact
from django.core.exceptions import ValidationError
from django import forms
from contact.widgets import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User




class ContactForm(forms.ModelForm):

    first_name = first_name
    last_name = last_name
    phone = phone
    email = email
    picture = picture
    """
        Classe usada para criada um fómulário para contacto
    """
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone',
                  'email', 'description', 'category',
                  'picture',)

        
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        
        if last_name == first_name:
            msg = ValidationError(
                    'O primeiro nome não pode ser igual ao segund', code='invalid'
                )
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)
        return super().clean()
        
        # Aqui estamos adicionando mensagem de erro fora de um campo
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
         
        if first_name == 'ABC':
            self.add_error('first_name', 
                ValidationError(
                    'Mensagem de Erro 2', code='invalid'
                )
            )
        return first_name
    
class  RegisterUser(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
      
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError(
                    'Já existe este email', code='invalid'
                )
            )
        return email
        

contact/views/contact_views.py
from django.shortcuts import render
from contact.models import Contact
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.core.paginator import Paginator

# Create your views here.

def index(request):

    # Função para listar os meus objetos por página. Em um página terá 10 objetos

    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)  # Show 10 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj' : page_obj,
               'site_title': 'Contactos - '}
    return render(
        request,
        'contact/index.html', 
        context
    )
 

def search(request):

    # Função para pesquisar objetos (pode-se buscar com first_name ou com last_name)
    
    search_value = request.GET.get('q', '').strip()
    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects.\
        filter(show=True).\
        filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value)
            ).\
        order_by('-id')
    
    paginator = Paginator(contacts, 10)  # Show 10 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj' : page_obj,
               'site_title': 'Search - ',
               'search_value': search_value}
    return render(
        request,
        'contact/index.html', 
        context
    )


def get_contact(request, contact_id):

    # Função para busca um deteminado objeto de acordo com o ID
    
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
        )
    
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact' : single_contact,
        'site_title': site_title
               }
    
    return render(
        request,
        'contact/get_contact.html', 
        context
    )

contact/views/create.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact
from django.contrib import messages

# Create your views here.



def create(request):
    """
        Função para criar um contacto
    """
    form_action = reverse('contact:create_contact')

    if request.method == 'POST':

        form = ContactForm(request.POST, request.FILES)
        print(request.POST)

        context = {
            'form' : form,
            'form_action' : form_action
            }
        
        if form.is_valid():
            contact = form.save()
            print('save')
            return redirect(
                'contact:update_contact', 
                contact_id=contact.pk
                )
        
        return render(
                request,
                'contact/create_contact.html', 
                context
                )
    
    context = {
            'form' : ContactForm(),
            'form_action' : form_action
            }
    return render(
        request,
        'contact/create_contact.html', 
        context
    )

# Analisar a viwes que está sendo redirecionada.
 
def update(request, contact_id): 
    """
        Função para atualiar um contacto
    """
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse('contact:update_contact', args=(contact_id,))
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact,)
        context = {
            'form' : form,
            'form_action' : form_action
            }
        if form.is_valid():
            contact = form.save()
            messages.success(request, 'Contacto atualizado com sucesso!')
            return redirect('contact:get_contact', contact.id)
        return render(request,'contact/create_contact.html', context)
    context = {
            'form' : ContactForm(instance=contact),
            'form_action' : form_action
            }
    return render(
        request,
        'contact/create_contact.html', 
        context
    )


def delete(request, contact_id): 
    """
        Função para atualiar um contacto
    """
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    confirmation = request.POST.get('confirmation', 'no')
    print('confirmation', confirmation)

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    context = {
        'contact': contact,
        'confirmation':confirmation
        }
    
    return render(request, 'contact/get_contact.html', context)
    
    

contact/views/create_user.py
from contact.forms import RegisterUser
from django.contrib.auth import (login, logout)
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib import messages

def create_user(request):
    form = RegisterUser()

    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuário criado com sucesso!")  
            return redirect('contact:login')  
    return render(
        request,
        'contact/create_user.html',
        {
            'form' : form
        }
        )

def login_user(request): # continuar aqui, criando _login de user
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, f'Olá {user}') 
            return redirect('contact:index')
        messages.error(request, 'Login Inváliddo')
    return render(
        request,
        'contact/login_user.html',
        {
            'form' : form
        }
        )

def logout_user(request):
    logout(request)
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
    
        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>Phone: </b>{{contact.phone}}</p>
        <p><b>E-mail: </b>{{contact.email}}</p>
        <p><b>Date Createde: </b>{{contact.email}}</p>
        <p><b>Description: </b>{{contact.description}}</p>
        <p><b>category: </b>{{contact.category.name}}</p>
        {% if contact.picture %}
            <p><img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}"></p>
        {%else%}
            <p><img src="#" alt=""></p>
        {% endif %}

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update_contact' contact.id %}">
                Update
            </a> 

            <form action="{% url 'contact:delete_contact' contact.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden", name="confirmation", value="yes">
                    <button class="btn btn-link btn-delete" type="submit">
                        Confirmação?
                    </button>
                {% else %}
                    <button class="btn btn-link btn-delete" type="submit">
                        Delete
                    </button>
                {% endif %}
        </form>
        </div>
    </div>

{% endblock content %}

contact/templates/contact/create_contact.html
{% extends "global/base.html" %}

{% block content %}

  <div class="form-wrapper">

    <h2>Contacto</h2>

    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data">

        {% csrf_token %}
      <div class="form-content">
        {% for field in form %}
          <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
              {{field}}
              {{field.errors}}

              {%if field.help_text%}
                <p class="help-text">
                    {{field.help_text}}
                </p>
              {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group">
              <img src="{{field.value.url}}" alt="{{contact.first_name}} {{contact.last_name}}">
            </div>
          {% endif %}
        {% endfor %}
      </div>
        

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
        <button class="btn" type="submit">Send</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

contact/templates/contact/create_user.html
{% extends "global/base.html" %}

{% block content %}

  <div class="form-wrapper">

    <h2>Register User</h2>

    {% include "contact/partials/_user-form.html" %}
    
  </div>
{% endblock content %}

contact/templates/contact/get_contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>
    
        <p><b>ID: </b>{{contact.id}}</p>
        <p><b>Phone: </b>{{contact.phone}}</p>
        <p><b>E-mail: </b>{{contact.email}}</p>
        <p><b>Date Createde: </b>{{contact.email}}</p>
        <p><b>Description: </b>{{contact.description}}</p>
        <p><b>category: </b>{{contact.category.name}}</p>
        {% if contact.picture %}
            <p><img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}"></p>
        {%else%}
            <p><img src="#" alt=""></p>
        {% endif %}

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update_contact' contact.id %}">
                Update
            </a> 

            <form action="{% url 'contact:delete_contact' contact.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden", name="confirmation", value="yes">
                    <button class="btn btn-link btn-delete" type="submit">
                        Confirmação?
                    </button>
                {% else %}
                    <button class="btn btn-link btn-delete" type="submit">
                        Delete
                    </button>
                {% endif %}
        </form>
        </div>
    </div>

{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
    {% if page_obj %}
        <div class="responsive_table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contacts
                </caption>

                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">First_name</th>
                        <th class="table-header">Last_name</th>
                        <th class="table-header">Phone</th>
                        <th class="table-header">Email</th>
                    </tr>
                </thead>

                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a href= "{% url 'contact:get_contact' contact.id %}" 
                                class="table-link">{{contact.id}}</a>
                            </td>
                            <td class="table-cel">
                                {{contact.first_name}}
                            </td>
                            <td class="table-cel">
                                {{contact.last_name}}
                            </td>
                            <td class="table-cel">
                                {{contact.phone}}
                            </td>
                            <td class="table-cel">
                                {{contact.email}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>
            
        </div>

        {% include 'global/partials/__pagination.html'%}
        
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
                Nenhum contacto não encontrado
            </h1>
        </div>
    {% endif %}

{% endblock content %}

contact/templates/contact/login_user.html
{% extends "global/base.html" %}

{% block content %}

  <div class="form-wrapper">

    <h2>Login {{user}} {{user.is_authenticated}}</h2>

    {% if user.is_authenticated %}
      <p>
        Você fez login como {{user}} clica
         <a href="{% url "contact:logout" %}">aqui</a> para sair
      </p>

    {% else %}
      {% include "contact/partials/_user-form.html" %}
    {% endif %}
    
  </div>
{% endblock content %}